USE [master]
GO

/****** Object:  Database [FluxoCaixa.Data]    Script Date: 30/11/2023 12:24:48 ******/
CREATE DATABASE [FluxoCaixa.Data]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FluxoCaixa.Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FluxoCaixa.Data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FluxoCaixa.Data_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FluxoCaixa.Data_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FluxoCaixa.Data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FluxoCaixa.Data] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET ARITHABORT OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FluxoCaixa.Data] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FluxoCaixa.Data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FluxoCaixa.Data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FluxoCaixa.Data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FluxoCaixa.Data] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FluxoCaixa.Data] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FluxoCaixa.Data] SET  MULTI_USER 
GO

ALTER DATABASE [FluxoCaixa.Data] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FluxoCaixa.Data] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FluxoCaixa.Data] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FluxoCaixa.Data] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FluxoCaixa.Data] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FluxoCaixa.Data] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FluxoCaixa.Data] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FluxoCaixa.Data] SET  READ_WRITE 
GO

